### ISSUE TITLE
Актуальность версии

### ISSUE THREAD

**Issue by demetrodon** [Vaskevych/Freelancehunt-chrome#4]
На данный момент версия что в репозитории актуальна относительно той что в chrome web store?
Так как там версия 2.2, которая была измена 8 декабря, здесь 2.0, а последний коммит был 2 месяца назад.

**Comment by Vaskevych** [comment]
Сделаю на днях новый коммит, просто занят большым проектом.))

**Comment by demetrodon** [comment]
Ну что там?)
